/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ColabRouteImport } from './routes/colab'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AppsIndexRouteImport } from './routes/apps.index'
import { Route as AppsAppIdRouteImport } from './routes/apps.$appId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ColabRoute = ColabRouteImport.update({
  id: '/colab',
  path: '/colab',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/colab': typeof ColabRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/colab': typeof ColabRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/apps': typeof AppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/colab': typeof ColabRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/chat'
    | '/colab'
    | '/settings'
    | '/apps/$appId'
    | '/apps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/chat'
    | '/colab'
    | '/settings'
    | '/apps/$appId'
    | '/apps'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/chat'
    | '/colab'
    | '/settings'
    | '/apps/$appId'
    | '/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ChatRoute: typeof ChatRoute
  ColabRoute: typeof ColabRoute
  SettingsRoute: typeof SettingsRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
  AppsIndexRoute: typeof AppsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colab': {
      id: '/colab'
      path: '/colab'
      fullPath: '/colab'
      preLoaderRoute: typeof ColabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ChatRoute: ChatRoute,
  ColabRoute: ColabRoute,
  SettingsRoute: SettingsRoute,
  AppsAppIdRoute: AppsAppIdRoute,
  AppsIndexRoute: AppsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
